// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iksdupnkdrqnktqcuuss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrc2R1cG5rZHJxbmt0cWN1dXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODQ4NTgsImV4cCI6MjA2NDQ2MDg1OH0.cQFY2x7ONDSviUyKRw6GNke5_PrLVIgEgwZT6DIXhec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);